http://www.baseball-reference.com/teams/KCR/2016.shtml

In [1]:
import pandas as pd

In [2]:
import pandas, numpy
import requests, bs4
import re, os
import matplotlib.pyplot as plt
from pylab import *

In [3]:
import pandas, numpy
import requests, bs4
import re, os

## This is the best place to get started.
## This function simply takes a url and provides the ids
## from the html tables that the code provided here can access.
## Using findTables is great for determining options for the
## pullTable function for the tableID argument.
def findTables(url):
    res = requests.get('https://www.basketball-reference.com/teams/MIL/2023.html')
    ## The next two lines get around the issue with comments breaking the parsing.
    comm = re.compile("<!--|-->")
    soup = bs4.BeautifulSoup(comm.sub("", res.text), 'lxml')
    divs = soup.findAll('div', id = "content")
    divs = divs[0].findAll("div", id=re.compile("^all"))
    ids = []
    for div in divs:
        searchme = str(div.findAll("table"))
        x = searchme[searchme.find("id=") + 3: searchme.find(">")]
        x = x.replace("\"", "")
        if len(x) > 0:
            ids.append(x)
    return(ids)
## For example:
## findTables("http://www.baseball-reference.com/teams/KCR/2016.shtml")

In [4]:
findTables("https://www.basketball-reference.com/teams/MIL/2023.html")

['roster',
 'injuries',
 'table class=nohover',
 'team_and_opponent',
 'team_misc',
 'per_game',
 'totals',
 'per_minute',
 'per_poss',
 'advanced',
 'adj_shooting',
 'shooting',
 'pbp',
 'table class=no_columns',
 'salaries2',
 'draft-rights']

In [5]:
## Pulls a single table from a url provided by the user.
## The desired table should be specified by tableID.
## This function is used in all functions that do more complicated pulls.
def pullTable(url, tableID):
    res = requests.get(url)
    ## Work around comments
    comm = re.compile("<!--|-->")
    soup = bs4.BeautifulSoup(comm.sub("", res.text), 'lxml')
    tables = soup.findAll('table', id = tableID)
    data_rows = tables[0].findAll('tr')
    data_header = tables[0].findAll('thead')
    data_header = data_header[0].findAll("tr")
    data_header = data_header[0].findAll("th")
    game_data = [[td.getText() for td in data_rows[i].findAll(['th','td'])]
        for i in range(len(data_rows))
        ]
    data = pandas.DataFrame(game_data)
    header = []
    for i in range(len(data.columns)):
        header.append(data_header[i].getText())
    data.columns = header
    data = data.loc[data[header[0]] != header[0]]
    data = data.reset_index(drop = True)
    return(data)
## For example:
url = "https://www.basketball-reference.com/teams/MIL/2023.html"
## pullTable(url, "team_batting")

In [6]:
#pullTable(url, "roster")
#pullTable(url, "injuries")
#pullTable(url, "table class=nohover")
#pullTable(url, "team_and_opponent")
#pullTable(url, "team_misc")
#pullTable(url, "per_game")
#pullTable(url, "totals")
#pullTable(url, "per_minute")
#pullTable(url, "per_poss")
#pullTable(url, "advanced")
#pullTable(url, "adj_shooting")
#pullTable(url, "shooting")
#pullTable(url, "pbp")
#pullTable(url, "table class=no_columns")
#pullTable(url, "salaries2")
#pullTable(url, "draft-rights")

In [20]:
#pullTable(url, "salaries2")

In [8]:
##df_salary = pullTable(url, "salaries2")
#df_salary
#df_salary.iloc[0:1]
#list(df_salary.columns)
#df_salary.columns
#df_salary['Salary']

In [9]:
df_totals = pullTable(url, "totals")
#df_totals
#df_totals.iloc[0:1]
#list(df_totals.columns)
#df_totals.columns
#df_totals['']

In [10]:
#df_totals.sort_values(by=['PTS'])

In [11]:
df = df_totals

In [12]:
# Remove rows with all 0s in a Dataframe
#df.loc[~(df==0).all(axis=1)]

In [13]:
# print(df.dtypes)
# convert 
#df = df.astype({'PTS':'int'})
#print(df.dtypes)

In [14]:
#TOTALS ROW 
#df.iloc[-1:]

In [15]:

#DROP TOTALS ROW
df = df[:-1]
#df

In [16]:
# print(df.dtypes)
# CONVERT PTS 
df = df.astype({'Age':'int', 'G':'int', 'GS':'int','MP':'int','FG':'int','FGA':'int','3P':'int','ORB':'int','DRB':'int','TRB':'int','AST':'int','STL':'int','BLK':'int','TOV':'int','PF':'int','PTS':'int','3PA':'int','2P':'int','FT':'int','FTA':'int','2PA':'int'})
#print(df.dtypes)

In [17]:
print(df.dtypes)

Rk      object
Â        object
Age      int32
G        int32
GS       int32
MP       int32
FG       int32
FGA      int32
FG%     object
3P       int32
3PA      int32
3P%     object
2P       int32
2PA      int32
2P%     object
eFG%    object
FT       int32
FTA      int32
FT%     object
ORB      int32
DRB      int32
TRB      int32
AST      int32
STL      int32
BLK      int32
TOV      int32
PF       int32
PTS      int32
dtype: object

In [23]:
df.sort_values(by=['3P'], ascending=False)

,Rk,,Age,G,GS,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Jrue Holiday,32,9,9,302,67,154,.435,22,...,.857,12,39,51,72,14,6,21,15,180
1,2,Brook Lopez,34,9,9,273,52,104,.500,21,...,.833,20,39,59,9,6,23,13,25,135
3,4,Grayson Allen,27,9,8,233,27,67,.403,18,...,.900,7,21,28,21,9,1,13,11,90
4,5,Bobby Portis,27,9,1,232,50,108,.463,12,...,.727,26,75,101,18,3,3,8,12,120
5,6,Jevon Carter,27,9,9,215,18,50,.360,12,...,1.000,6,14,20,14,15,5,10,26,51
7,8,Jordan Nwora,24,9,0,151,18,50,.360,9,...,1.000,6,23,29,5,4,0,10,10,53
2,3,Giannis Antetokounmpo,28,8,8,268,94,170,.553,8,...,.631,16,87,103,46,8,12,25,23,261
8,9,Wesley Matthews,36,9,0,135,10,31,.323,8,...,.750,12,11,23,6,6,2,5,15,31
6,7,George Hill,36,9,0,192,15,34,.441,5,...,.667,3,14,17,22,2,0,6,16,47
9,10,Serge Ibaka,33,7,0,74,8,18,.444,3,...,.833,4,14,18,2,0,5,6,11,24
10,11,MarJon Beauchamp,22,6,1,72,9,26,.346,3,...,.600,4,11,15,1,3,1,8,11,24
11,12,Thanasis Antetokounmpo,30,4,0,8,0,0,,0,...,,0,2,2,0,0,1,0,1,0
12,13,A.J. Green,23,1,0,2,0,0,,0,...,,0,0,0,1,0,0,0,0,0
13,14,Sandro Mamukelashvili,23,1,0,2,0,0,,0,...,,0,0,0,0,0,0,1,0,0